### ISSUE TITLE
RabbitMQ and etcd packages

### ISSUE THREAD

**Issue by laurentluce** [kurtosis-tech/awesome-kurtosis#123]
I wrote a [RabbitMQ](https://github.com/laurentluce/kurtosis-rabbitmq-package) and an [etcd](https://github.com/laurentluce/kurtosis-etcd-package) Kurtosis package.  Let me know if you are interested, and I can work with you to transfer the package repos under kurtosis-tech.

**Comment by Peeeekay** [comment]
Thanks for reaching out and taking time on creating these packages. I can work with you on this; it would be awesome if you can create 2 PRs - one for each package against awesome-kurtosis.

**Comment by laurentluce** [comment]
I opened the first PR for the etcd package: #124

**Comment by laurentluce** [comment]
Both etcd and RabbitMQ packages have been ported from @laurentluce to @kurtosis-tech.
