### ISSUE TITLE
Make subpackage checks opt-in by default

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/awesome-kurtosis#87]
PROBLEM:
- Each subdirectory is a separate CircleCI job, so someone adding a new subdirectory needs to remember to add a new CircleCI job to test it
- The check that tries to skip the directory if it doesn't have changes will silently skip & pass if the user copy-pastes the name  (this was the case with `redis-voting-app`)
- The `check_latest_version` requires someone to remember to add the new subdirectory to it (also the case with `redis-voting-app`)

SOLUTIONIZING:
Have a single `check` job with a `for` loop that iterates over all subdirectories by default, skipping the directories that don't have changes (coded in the `for` loop, so impossible to get a mismatch with dir name)

Have `check_latest_version` do the same with a `for` loop, so users can't forget to add it.

**Comment by h4ck3rk3y** [comment]
Note as a part of this we should also run `kurtosis clean -a` between jobs so that there ins't resource contention

Also note we have temporarily updated resource_class to xlarge, we should remove that after this for loop is in place.

**Comment by h4ck3rk3y** [comment]
Perhaps also use YAML anchors to cleanup CI as a part of this

**Comment by h4ck3rk3y** [comment]
@victorcolombo probably add more parameters; to test other permutations (maybe could be a separate ticket)
